In [1]:
import numpy as np
import pandas as pd
import os
import math
import time
import h5py

current_path = os.getcwd()
print("current_path:", current_path),print()

bottom=30.012
up=30.4439     
left=119.8691 
right=120.461
blockCount=50

wideRange=right-left
heightRange=up-bottom
wideDistance=wideRange/blockCount
heightDistance=heightRange/blockCount

data = pd.read_csv("filesList.csv")
listName = data['filename']
print("listName:", type(listName[0]))

def deviceFile():
    fileList = []
    for i in range(24):
        if len(str(i))<2:
            fileList.append('DeviceID'+'0'+str(i))
        else:
            fileList.append('DeviceID'+str(i))
    return fileList

fileList = deviceFile()
print("fileList:", fileList),print()

def deviceId(m,n):
    deviceList = []
    path = current_path + '/'+listName[m]+'/'+fileList[n]+'/'
    for file in os.listdir(path):
        deviceList.append(file)
    return deviceList,path

deviceList,path = deviceId(0,1)
print("len(deviceList):", len(deviceList))
print("path:", path)
print(listName[0])

C:\Users\liuliyian\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


current_path: Z:\liyanliu\traDataNew

listName: <class 'str'>
fileList: ['DeviceID00', 'DeviceID01', 'DeviceID02', 'DeviceID03', 'DeviceID04', 'DeviceID05', 'DeviceID06', 'DeviceID07', 'DeviceID08', 'DeviceID09', 'DeviceID10', 'DeviceID11', 'DeviceID12', 'DeviceID13', 'DeviceID14', 'DeviceID15', 'DeviceID16', 'DeviceID17', 'DeviceID18', 'DeviceID19', 'DeviceID20', 'DeviceID21', 'DeviceID22', 'DeviceID23']

len(deviceList): 13272
path: Z:\liyanliu\traDataNew/d01_w4/DeviceID01/
d01_w4


In [2]:
print("开始运行......")
now = time.clock()

def trafficVolum(m):
    TV = np.zeros((24,50,50))
    for n in range(24):
    # for n in range(0,2):
        deviceList,path = deviceId(m,n) 
        print("len(deviceList):", len(deviceList))
        print('path:',path)
        trafficVolume = np.zeros((50,50))
        for i in range(len(deviceList)):
    #     for i in range(0,3):
            data = pd.read_csv(path+deviceList[i])
    #         print("deviceList[i]:", deviceList[i])
            df = pd.DataFrame(data = data)
            rowList = [min(math.floor(row),49) for row in (df.Latitude-bottom)/heightDistance]
            colList = [min(math.floor(col),49) for col in (df.Longitude-left)/wideDistance]
            grid = list(set((str(rowList[i])+','+str(colList[i])) for i in range(len(rowList))))
    #         print(len(grid))
            for j in range(len(grid)):
                row = int(grid[j].split(',')[0])
                col = int(grid[j].split(',')[1])
                trafficVolume[row][col] +=1
    #     trafficVoume = np.array(trafficVolume)
        print(sum(sum(trafficVolume)))
        TV[n]=np.array(trafficVolume)

    f = h5py.File(current_path + '/d01_w4/trafficVolume/'+ listName[m]+'_M50x50_trafficVolume.hdf5', "w")
    print(current_path + '/d01_w4/trafficVolume/'+ listName[m]+'_M50x50_trafficVolume.hdf5')
    f['data'] = TV
    
trafficVolum(17)    
    
print("运行完毕！耗时%f分钟。"%((time.clock()-now)/60))

开始运行......
len(deviceList): 13736
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID00/
138012.0
len(deviceList): 14067
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID01/
213494.0
len(deviceList): 14326
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID02/
262408.0
len(deviceList): 14603
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID03/
300832.0
len(deviceList): 15195
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID04/
333127.0
len(deviceList): 16396
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID05/
376091.0
len(deviceList): 17913
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID06/
444532.0
len(deviceList): 19218
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID07/
532164.0
len(deviceList): 20026
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID08/
622906.0
len(deviceList): 20498
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID09/
710106.0
len(deviceList): 20953
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID10/
797680.0
len(deviceList): 21254
path: Z:\liyanliu\traDataNew/d18_w7/DeviceID11/
887469.0
len(deviceList): 21508
path: 

In [5]:
f = h5py.File(current_path + '/d01_w4/trafficVolume/'+ listName[0]+'_M50x50_trafficVolume.hdf5')
dataset = []
for ke in f.keys():
    print(ke,f[ke].shape)
    dataset.append(f[ke])
print(dataset[0][0])
print(sum(sum(dataset[0][0])))
print(sum(sum(dataset[0][1])))

data (24, 50, 50)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 2. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
153632.0
246117.0


In [3]:
import numpy as np
import pandas as pd
import h5py
import os
current_path = os.getcwd()

data = pd.read_csv("filesList.csv")
listName = data['filename']
print("listName:", type(listName[0]))

# 得到tensor,  location X day X time = trafficVolume,  (2500X7X24)
def obtainTensor(listName):
    dataset = []
    for i in range(7):
        f = h5py.File(current_path + '/d01_w4/trafficVolume/'+ listName[i]+'_M50x50_trafficVolume.hdf5')
        for ke in f.keys():
            dataset.append(f[ke])
    print("len(dataset):", len(dataset))

    num = 0
    for n in range(len(dataset)):
        for j in range(len(dataset[0])):
#             print(n,j,dataset[n][j].shape)
            data = dataset[n][j].reshape(1,2500)[0]
            index = data.nonzero()[0] # 得到data中非零元素的索引
            print(index,len(index))
            num += len(index)
            value = [int(data[i]) for i in index] # 得到data中与索引相对应的非零元素的值
            print(len(value)),print()
    #         print(current_path+'/tensorData/loc_day_time.csv')
            tensorPath = current_path+'/tensorData/loc_day_time.csv'
            with open(tensorPath,'a') as f:
                for i in range(len(index)):
                    f.write(str(index[i])+','+str(n+1)+','+str(j+1)+','+str(value[i])+'\n')
    print("num:",num)

obtainTensor(listName)

listName: <class 'str'>
len(dataset): 7
[   3    4    5 ... 2493 2494 2499] 1571
1571

[   3    4    5 ... 2493 2494 2499] 1689
1689

[   3    4    5 ... 2493 2494 2499] 1755
1755

[   3    4    5 ... 2493 2494 2499] 1793
1793

[   3    4    5 ... 2493 2494 2499] 1840
1840

[   3    4    5 ... 2493 2494 2499] 1859
1859

[   3    4    5 ... 2493 2494 2499] 1889
1889

[   3    4    5 ... 2493 2494 2499] 1924
1924

[   3    4    5 ... 2493 2494 2499] 1955
1955

[   3    4    5 ... 2493 2494 2499] 1987
1987

[   3    4    5 ... 2493 2494 2499] 2002
2002

[   3    4    5 ... 2493 2494 2499] 2020
2020

[   3    4    5 ... 2493 2494 2499] 2034
2034

[   3    4    5 ... 2493 2494 2499] 2054
2054

[   3    4    5 ... 2493 2494 2499] 2071
2071

[   3    4    5 ... 2493 2494 2499] 2101
2101

[   3    4    5 ... 2493 2494 2499] 2116
2116

[   3    4    5 ... 2493 2494 2499] 2129
2129

[   3    4    5 ... 2494 2497 2499] 2138
2138

[   3    4    5 ... 2494 2497 2499] 2146
2146

[   1    2    3 ... 